name: "3. Generate Synthetic Data"

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate synthetic dataset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Download workspaces summary artifact into .state
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: provision_workspaces.yml
          name: bff-workspaces-summary
          path: .state
          workflow_conclusion: success
          branch: main

##### Add notebooks_to_create parameter here, for example: ######
#notebooks_to_create = [
#    {
#        "displayName": "0.GenerateData",
#        "description": "Synthetic data generation",
#        "file": "notebooks/generate_data.ipynb",
#        "workspaces": ["BFF Controller"],
#    }
#]
      - name: Provision notebook
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#notebooks_to_create        
        run: |
          python ./scripts/provision_notebooks.py

      - name: Run notebook to generate synthetic data
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DB: ${{ secrets.AZURE_SQL_DB }}
        run: |
          python ./scripts/generate_synthetic_data.py

      - name: Upload generated datasets list
        uses: actions/upload-artifact@v4
        with:
          name: datasets
          path: .state/datasets.json
          if-no-files-found: error
          include-hidden-files: true
